/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ztiany_sample1_JNIObj */

#ifndef _Included_com_ztiany_sample1_JNIObj
#define _Included_com_ztiany_sample1_JNIObj
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ztiany_sample1_JNIObj
 * Method:    getMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ztiany_sample1_JNIObj_getMessage
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
