/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ztiany_bsdiff_JniUtils */

#ifndef _Included_com_ztiany_bsdiff_JniUtils
#define _Included_com_ztiany_bsdiff_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ztiany_bsdiff_JniUtils
 * Method:    doDiff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ztiany_bsdiff_JniUtils_doDiff
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
