/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ztiany_bsdiffapp_utils_PatchUtils */

#ifndef _Included_com_ztiany_bsdiffapp_utils_PatchUtils
#define _Included_com_ztiany_bsdiffapp_utils_PatchUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ztiany_bsdiffapp_utils_PatchUtils
 * Method:    mergeFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ztiany_bsdiffapp_utils_PatchUtils_mergeFile
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
