/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ztiany_sample2_JniUtils */

#ifndef _Included_com_ztiany_sample2_JniUtils
#define _Included_com_ztiany_sample2_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ztiany_sample2_JniUtils
 * Method:    getMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ztiany_sample2_JniUtils_getMessage
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
